# Generated by Django 4.0.2 on 2022-06-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_q_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_images',
        ),
    ]
